import { expect, test } from '@playwright/test'

test('abre o cadastro público', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: /Quem acolhe/ })).toBeVisible()
  await page.getByRole('button', { name: /Iniciar meu cadastro/ }).click()
  await expect(page.getByRole('heading', { name: 'Identificação' })).toBeVisible()
  await expect(page.getByText('Etapa 1 de 4')).toBeVisible()
})

test('super admin entra e consulta os cadastros', async ({ page }) => {
  await page.goto('/#admin')
  await page.getByRole('button', { name: /Entrar no painel/ }).click()
  await expect(page.getByRole('heading', { name: 'Visão geral' })).toBeVisible()
  await expect(page.getByText('Mariana Alves da Silva')).toBeVisible()
  await page.getByText('Mariana Alves da Silva').click()
  await expect(page.getByText('DETALHES DO CADASTRO')).toBeVisible()
  await expect(page.getByText('Psicopedagogia', { exact: true })).toBeVisible()
})

test('exibe filiação, povo indígena, formações repetíveis e itinerários', async ({ page }) => {
  await page.goto('/#cadastro')
  await page.getByLabel('Nome completo*').fill('Teste da Silva')
  await page.getByLabel('CPF*').fill('52998224725')
  await page.getByLabel('Data de nascimento*').fill('1990-01-10')
  await page.getByLabel('E-mail*').fill('teste@exemplo.com')
  await page.getByLabel('Telefone / WhatsApp*').fill('(61) 99999-9999')
  await page.getByLabel('Nome completo da filiação 1').fill('Maria da Silva')
  await page.locator('label.choice').filter({ hasText: /^Masculino$/ }).click()
  await page.locator('label.choice').filter({ hasText: /^Indígena$/ }).click()
  await expect(page.getByLabel('Nome do povo / tribo indígena*')).toBeVisible()
  await page.getByLabel('Nome do povo / tribo indígena*').fill('Guarani')
  await page.getByRole('button', { name: 'Continuar' }).click()

  await page.getByLabel('CEP*').fill('70000-000')
  await page.getByLabel('Município*').fill('Brasília')
  await page.getByLabel('UF*').fill('DF')
  await page.locator('label.choice').filter({ hasText: /^Urbana$/ }).click()
  await page.getByRole('button', { name: 'Continuar' }).click()

  await page.getByLabel('Maior nível de escolaridade concluído*').selectOption({ label: 'Educação superior' })
  await page.getByRole('button', { name: /Adicionar formação$/ }).click()
  await expect(page.getByText('Formação pedagógica 2', { exact: false })).toBeVisible()
  await page.getByRole('button', { name: /Adicionar curso superior/ }).click()
  await expect(page.getByText('Curso superior 2')).toBeVisible()
  await page.getByRole('button', { name: /Adicionar pós-graduação/ }).click()
  await expect(page.getByText('Pós-graduação 2', { exact: false })).toBeVisible()
  await page.getByRole('button', { name: /Adicionar outro curso/ }).click()
  await expect(page.getByLabel('Outro curso 2')).toBeVisible()
  await page.getByLabel('Nome do curso*').first().fill('Pedagogia')
  await page.getByRole('button', { name: 'Continuar' }).click()

  await expect(page.locator('label.choice').filter({ hasText: /^Docente$/ })).toBeVisible()
  await expect(page.locator('label.choice').filter({ hasText: /^Guia-intérprete$/ })).toBeVisible()
  await page.locator('label.choice').filter({ hasText: /^Docente$/ }).click()
  await page.locator('label.choice').filter({ hasText: /^40h$/ }).click()
  await page.locator('label.choice').filter({ hasText: /^Concursado\/efetivo\/estável$/ }).click()
  await page.locator('input[name="ifa"][value="Sim"]').locator('..').click()
  await expect(page.getByLabel('Área do itinerário formativo*')).toBeVisible()
  await page.locator('input[name="iftp"][value="Sim"]').locator('..').click()
  await expect(page.getByLabel('Área da formação técnica e profissional*')).toBeVisible()
})

test('habilita profissionais, relatórios e questionário do aluno no painel', async ({ page }) => {
  await page.goto('/#admin')
  await page.getByRole('button', { name: /Entrar no painel/ }).click()

  await page.getByRole('button', { name: /Profissionais/ }).click()
  await expect(page.getByRole('heading', { name: 'Profissionais', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: /Baixar planilha/ })).toBeVisible()

  await page.getByRole('button', { name: 'Relatórios' }).click()
  await expect(page.getByRole('heading', { name: 'Relatórios' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Planilha de profissionais' })).toBeVisible()

  await page.getByRole('button', { name: /Questionário do aluno/ }).click()
  await expect(page.getByRole('heading', { name: 'Cadastrar aluno(a)' })).toBeVisible()
  await expect(page.getByLabel('Código da escola*')).toBeVisible()
  await expect(page.getByLabel('CPF (somente números)')).toBeVisible()
})

test('valida cpf, e-mail e celular no cadastro profissional', async ({ page }) => {
  await page.goto('/#cadastro')
  await page.getByLabel('Nome completo*').fill('Pessoa de Teste')
  await page.getByLabel('CPF*').fill('11111111111')
  await page.getByLabel('Data de nascimento*').fill('1990-01-10')
  await page.getByLabel('E-mail*').fill('email-invalido')
  await page.getByLabel('Telefone / WhatsApp*').fill('123')
  await page.locator('label.choice').filter({ hasText: /^Masculino$/ }).click()
  await page.locator('label.choice').filter({ hasText: /^Branca$/ }).click()
  await page.getByRole('button', { name: 'Continuar' }).click()
  await expect(page.getByText('CPF inválido. Digite os 11 números.')).toBeVisible()
  await expect(page.getByText('Informe um e-mail válido.')).toBeVisible()
  await expect(page.getByText('Informe um celular válido com DDD.')).toBeVisible()
})
